export const ActionTypes = {
  SET_MOVIES: "SET_MOVIES",
  SELECTED_CATEGORY_MOVIE: "SELECTED_CATEGORY_MOVIE",
  SELECTED_CATEGORY_TV: "SELECTED_CATEGORY_TV",
  SELECTED_CATEGORY_PERSON: "SELECTED_CATEGORY_PERSON",
};
