export const ActionTypes = {
  SET_DATAS: "SET_DATAS",
  INCREMENT_VOTE: "INCREMENT_VOTE",
  DECREMENT_VOTE: "DECREMENT_VOTE",
  INCREMENT_CHILD_VOTE: "INCREMENT_CHILD_VOTE",
  DECREMENT_CHILD_VOTE: "DECREMENT_CHILD_VOTE",
};
